sudo: required
language: python
python: "3.3"
addons:
  apt:
    packages:
      - libluajit-5.1-dev
install:
  - pip install coverage codecov
  - python setup.py install
script:
  - echo "#!$(which coverage) run" > tmp
  - cat $(which pxmake) >> tmp
  - chmod +x tmp
  - mv tmp $(which pxmake)
  - pxmake --version
  - pxmake l versioninfo
  - pxmake l --backtrace tests/test.lua

after_success:
  - coverage combine $(find -name '.coverage')
  - codecov
